# Generated by Django 4.2.2 on 2023-06-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_task_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='photos'),
        ),
    ]
