# Generated by Django 4.2.2 on 2023-07-09 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_category_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
