# Generated by Django 4.2.2 on 2023-07-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_blacklistedtoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blacklistedtoken',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='blacklistedtoken',
            old_name='blacklisted_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='blacklistedtoken',
            name='user',
        ),
        migrations.AlterField(
            model_name='blacklistedtoken',
            name='token',
            field=models.TextField(unique=True),
        ),
    ]
