# Generated by Django 3.2.20 on 2023-09-02 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_topic_answers_remove_topic_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
