# Generated by Django 3.2.20 on 2023-09-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='photos'),
        ),
    ]
