# Generated by Django 3.2.20 on 2023-09-10 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_outstandingtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OutstandingToken',
        ),
    ]
