# Generated by Django 3.2.20 on 2023-09-10 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
