# Generated by Django 3.2.20 on 2023-09-10 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_customusergroup_customuserpermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuserpermission',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='customuserpermission',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUserGroup',
        ),
        migrations.DeleteModel(
            name='CustomUserPermission',
        ),
    ]
