# Generated by Django 3.2.20 on 2023-09-27 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
