# Generated by Django 3.2.20 on 2023-09-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_xboxtopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xboxtopic',
            name='author',
            field=models.CharField(max_length=255),
        ),
    ]
