# Generated by Django 3.2.20 on 2024-04-11 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0033_auto_20240411_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardingindicator',
            name='indicator_type',
        ),
        migrations.AddField(
            model_name='onboardingindicator',
            name='gaming_tutorial_viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onboardingindicator',
            name='notifications_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onboardingindicator',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onboardingindicator',
            name='terms_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='onboardingindicator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
