# Generated by Django 3.2.20 on 2024-04-11 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0034_auto_20240411_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOnboardingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_step_passed', models.BooleanField(default=False)),
                ('gaming_solutions_step_passed', models.BooleanField(default=False)),
                ('profile_step_passed', models.BooleanField(default=False)),
                ('support_step_passed', models.BooleanField(default=False)),
                ('settings_step_passed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
