# Generated by Django 3.2.20 on 2024-04-11 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_useronboardingprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useronboardingprogress',
            name='user',
        ),
        migrations.DeleteModel(
            name='OnboardingIndicator',
        ),
        migrations.DeleteModel(
            name='UserOnboardingProgress',
        ),
    ]
