# Generated by Django 3.2.20 on 2024-04-12 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0036_auto_20240411_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('terms_of_use', 'Terms of Use'), ('my_games', 'My Games Screen'), ('messages', 'Messages Screen'), ('profile_setup', 'Profile Setup'), ('notifications', 'Notifications Setup')], max_length=50)),
                ('marked_as_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
