# Generated by Django 3.2.20 on 2024-04-12 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_onboardingindicator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardingindicator',
            name='user',
        ),
    ]
